PRX/metrics.prx.org

- src/app/downloads/downloads.component.css
- src/app/downloads/downloads.component.spec.ts
- src/app/downloads/downloads.component.ts
- src/app/shared/filter/canned-range.component.spec.ts
- src/app/shared/filter/canned-range.component.ts
- src/app/shared/filter/date-range.component.css
- src/app/shared/filter/date-range.component.spec.ts
- src/app/shared/filter/date-range.component.ts
- src/app/shared/filter/interval.component.ts
- src/app/shared/util/date.util.spec.ts
- src/app/shared/util/date.util.ts
I've been opening tickets as we find things that are less than stellar with the first go round on this feature set. Several of these things seemed to be in similar categories, so this PR covers #31, #33, #34, #37, #40, and #41.
> many small fixes

- src/app/downloads/downloads.component.ts
- src/app/shared/filter/date/custom-date-range.component.spec.ts
- src/app/shared/filter/date/custom-date-range.component.ts
- src/app/shared/filter/date/date-range.component.spec.ts
- src/app/shared/filter/date/date-range.component.ts
- src/app/shared/filter/filter.component.spec.ts
- src/app/shared/util/date.util.ts
#49 to track the way users are using the date range and time picker controls
> google analytics date range events

- package.json
- src/app/downloads/downloads-table.component.css
- src/app/downloads/downloads-table.component.spec.ts
- src/app/downloads/downloads-table.component.ts
- src/app/shared/pipes/large-number.pipe.spec.ts
- src/app/shared/pipes/large-number.pipe.ts
- src/app/shared/shared.module.ts
- src/polyfills.ts
- yarn.lock
#57 to right align numbers in table and format with thousands separator
I didn't do anything with the chart number formatting yet, ticket: https://github.com/PRX/styleguide.prx.org/issues/69
Also seeing this issue below with the table when scrolled horizontally. Ticket: https://github.com/PRX/metrics.prx.org/issues/67
> number formatting and alignment in table

- package.json
- yarn.lock
This update to the styleguide addresses the episode selection for users that are already on metrics.
> address episode selection with styleguide v0.0.22

- .prxci
- buildspec.yml
- docker-compose-ci.yml
CI v2 for metrics https://github.com/PRX/internal/issues/132
> buildspec.yml for CI v2

- src/app/downloads/downloads-chart.component.ts
> only stacked charts are stacked

- src/app/app.module.ts
- src/app/app.routing.ts
- src/app/login/index.ts
- src/app/login/login.module.ts
- src/app/login/login.routing.ts
puts 'login' route into it's own component for expected route override ordering
> fix the login route

- package.json
- src/app/shared/paging/episode-page.component.css
- yarn.lock
> Pagers and footers

- src/assets/zendesk-widget.js
- src/index.pug
#181 adds the zendesk contact form widget
> adds zendesk widget script

- src/app/app.component.ts
it was trying to load episodes with an undefined series id
> don't load episodes until has the series id

- src/app/downloads/downloads-chart.component.ts
do over. I misinterpreted the requirements for #159 
For multi-line chart, any time the dots are visible they would be 3.25. For single line, any time the dots are visible they would be 3.75.
For multi-line chart the dots are visible when there are ≤ 20 data points per line, and when there are > 20 the dots are only visible on when hovering on that point.
For single-line chart the dots are visible when there are ≤ 40 data points, and when there are > 40 the dots are only visible when hovering on that point.
> chart point configuration

- src/app/downloads/downloads-table.component.html
- src/app/downloads/downloads-table.component.ts
- src/app/ngrx/reducers/index.ts
- src/app/shared/pipes/large-number.pipe.spec.ts
- src/app/shared/pipes/large-number.pipe.ts
- src/app/shared/util/date/date.util.ts
- src/app/shared/util/metrics.util.spec.ts
- src/app/shared/util/metrics.util.ts
> weighted average math

- src/app/shared/menu/date/date-range-summary.component.ts
> Use horizontal bar as range separator

- src/app/ngrx/effects/cms.effects.spec.ts
- src/app/ngrx/effects/cms.effects.ts
Default select all episodes and hopefully clear up some confusing decisions we made earlier with paging and episode selection.
> chart all episodes by default

- src/app/ngrx/effects/cms.effects.ts
Hit an edge case where I do have series, but they're all v3.
> Catch lack-of-v4-series

- src/app/downloads/downloads-table.component.css
- src/app/downloads/downloads-table.component.html
- src/app/shared/paging/episode-page.component.css
- src/app/shared/paging/episode-page.component.spec.ts
- src/app/shared/paging/episode-page.component.ts
* Rely on the styleguide for pager styles
* Change text of the show/hide toggle for episode table
* Add first/last page pagination buttons
* Pagination has a "sliding window" currently configured to 5 page links. Logic from http://jasonwatmore.com/post/2016/01/31/angularjs-pagination-example-with-logic-like-google
DO NOT MERGE till https://github.com/PRX/styleguide.prx.org/pull/90 is deployed.
> Pagination toolbar styles

- README.md
This is a small change to help anyone who may have the same issues I had trying to get metrics to run on a local dev environment.
> Minor update to readme file to help troubleshoot puma-dev issues

- package.json
- src/app/app.component.html
- src/app/app.component.spec.ts
- src/app/app.component.ts
- src/app/authorization/authorization.component.css
- src/app/authorization/authorization.component.ts
- src/app/authorization/index.ts
- src/app/login/login.module.ts
- src/app/login/login.routing.ts
- src/app/ngrx/effects/cms.effects.spec.ts
- src/app/ngrx/effects/cms.effects.ts
- yarn.lock
Similar to https://github.com/PRX/publish.prx.org/commit/709f15f5801366915894e6554b1274bcf525dfa4
Implements authorization check and adds the new navmenu app dropdown.
> Add styleguide authorization checks

- package.json
- src/app/shared/nav/nav-menu.component.css
- src/app/shared/util/chart.util.ts
- yarn.lock
> Update styleguide, colors

- package.json
- yarn.lock
depends on https://github.com/PRX/styleguide.prx.org/pull/107
> Bump styleguide version to 0.40

- src/app/downloads/downloads-chart-presentation.component.ts
- src/app/downloads/downloads.component.ts
- src/app/ngrx/effects/cms.effects.spec.ts
- src/app/ngrx/effects/cms.effects.ts
- src/app/ngrx/effects/routing.effects.spec.ts
- src/app/ngrx/effects/routing.effects.ts
- src/app/ngrx/reducers/selectors/podcast.selectors.ts
- src/app/shared/menu/chart-type.component.css
- src/app/shared/menu/chart-type.component.ts
- src/app/shared/menu/date/custom-date-range-dropdown.component.css
- src/app/shared/menu/date/custom-date-range-dropdown.component.ts
- src/app/shared/menu/date/standard-date-range-dropdown.component.css
- src/app/shared/menu/dropdown.css
- src/app/shared/menu/interval-dropdown.component.css
- src/app/shared/nav/nav-menu.component.css
- src/app/shared/nav/nav-menu.component.ts
- src/app/shared/podcast-nav/podcast-nav-dropdown.component.css
- src/app/shared/util/local-storage.util.ts
- src/assets/images/bt_bar-chart.svg
* default date range is now 28 days
* hover/focus state on dropdowns
* mobile page nav 100% width
* nudge dropdowns to screen edges on mobile
* sorts podcast/show list
* saves router state in local storage and retrieves last selected podcast seriesId
> design review

- src/app/shared/menu/date/standard-date-range.component.ts
> fixes date range list for ULM Calendar Weekly and Monthly intervals

- Dockerfile
Should be deployed with https://github.com/PRX/Infrastructure/pull/572
> Remove tini from Dockerfile
